version: '3.8'

services:
  app:
    build: .
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - PORT=5000
      - MONGO_DB_URL=mongodb://mongo:27017/chatflow
      - JWT_SECRET=your_super_secure_jwt_secret_here
      - FRONTEND_URL=http://localhost:3000
    depends_on:
      - mongo
    restart: unless-stopped
    networks:
      - chatapp-network

  mongo:
    image: mongo:7.0
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_DATABASE=chatflow
    volumes:
      - mongo_data:/data/db
    restart: unless-stopped
    networks:
      - chatapp-network

  mongo-express:
    image: mongo-express:latest
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo
      - ME_CONFIG_MONGODB_PORT=27017
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=password
    depends_on:
      - mongo
    restart: unless-stopped
    networks:
      - chatapp-network

volumes:
  mongo_data:

networks:
  chatapp-network:
    driver: bridge 